export const ROUTES = {
  DASHBOARD: '/',
  ADMIN: '/admin',
  MANAGE_TENANTS: '/admin/manage-tenants',
  ADD_STATE_ADMIN: '/admin/add-state-admin',
  CONFIGURE_SYSTEM: '/admin/configure-system',
  STATE_ADMIN: '/state-admin',
  STATE_ADMIN_OVERVIEW: '/state-admin',
  STATE_ADMIN_LANGUAGE: '/state-admin/language',
  STATE_ADMIN_WATER_NORMS: '/state-admin/water-norms',
  STATE_ADMIN_INTEGRATION: '/state-admin/integration',
  STATE_ADMIN_ESCALATIONS: '/state-admin/escalations',
  STATE_ADMIN_THRESHOLDS: '/state-admin/thresholds',
  STATE_ADMIN_NUDGES: '/state-admin/nudges-template',
  STATE_ADMIN_API_INGESTION: '/state-admin/api-ingestion',
  STATE_ADMIN_OPERATOR_SYNC: '/state-admin/operator-sync',
  STATE_ADMIN_ACTIVITY: '/state-admin/activity',
  // Auth routes
  LOGIN: '/login',
  LOGOUT: '/logout',
  SIGNUP: '/signup',
  RESET_PASSWORD: '/resetpassword',
} as const
