#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Only run lint-staged if there are changes in the frontend folder
if git diff --cached --name-only --diff-filter=ACM | grep -q "^frontend/"; then
  cd frontend && npx lint-staged
fi

